apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "example.org"
    }

    plugins {
      NodeAttestor "k8s_sat" {
        plugin_data {
          # NOTE: Change this to your cluster name
          cluster = "minikube"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          # Defaults to the secure kubelet port by default.
          # Minikube does not have a cert in the cluster CA bundle that
          # can authenticate the kubelet cert, so skip validation.
          skip_kubelet_verification = true
        }
      }

      SVIDStore "sconecas_sessionmanager" {
        plugin_data {
          cas_connection_string = "https://5-6-0.scone-cas.cf:8081"
          cas_client_certificate = "/run/spire/config/session.crt"
          cas_client_key = "/run/spire/config/session.key"
          trust_anchor_certificate = "/run/spire/config/trustanchor.pem"

          cas_predecessor_dir = "/run/spire/data/store-svid-scone"
          svid_session_template_file = "/run/spire/config/svid_session_template.yaml"
          bundle_session_template_file = "/run/spire/config/ca_session_template.yaml"
          federated_bundles_session_template_file = "/run/spire/config/fed_bundles_session_template.yaml"
        }
      }

    }
  session.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIUV82WVdi2ue65tgW4EYd4IH16aYIwDQYJKoZIhvcNAQEL
    BQAwVjELMAkGA1UEBhMCRVUxDDAKBgNVBAgMA0NBUzEPMA0GA1UEBwwGQ0xJRU5U
    MREwDwYDVQQKDAhJbnRlcm5ldDEVMBMGA1UEAwwMc2NvbnRhaW4uY29tMB4XDTIw
    MDUwODE0MzA1NVoXDTIxMDUwODE0MzA1NVowVjELMAkGA1UEBhMCRVUxDDAKBgNV
    BAgMA0NBUzEPMA0GA1UEBwwGQ0xJRU5UMREwDwYDVQQKDAhJbnRlcm5ldDEVMBMG
    A1UEAwwMc2NvbnRhaW4uY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEAz9zahyoCRcmhm03oG4WuJhZcDCnvQslAQhmcaJZKn3ng4yCXKOs3DqWK5tM/
    eTMOYTU022Njg/kYYzczwVp2fOlDZ3Xlf6JVc27sDcUET/FZoQgbCFY20SojYSa6
    cogoNIYttDdc3VBzKQTiB7QkGLB49OxJExZaOqZHJ4YyP7EUHwD0B1wRGzN1Hqz1
    5LVX52KhOZ932WhT25+VV1pzDhKtcKdMw1buut/ukFYLuuFNEDblNAcRi3j9+Poz
    HGD6wTm/BeoH6w780bsJEi/kg38wAlcKlM1eh0x4i4XufxPqddPlxtEA2CSXvcrw
    81st5apWEK6j3XqUZHFZjz+Aqs62OgJnzXh7idmbfEZNTG0qhaImDHdCz1+z4ELw
    DL17w2n2SvdWBEEqwCp80pCMVBY+gf1/RhSns87LczdpsD6p8ZXPJTij3YahT7KM
    H0ZsQ8npZC6Vl+bzXRlJPGK5mfTVsBVYI8zt6CIzrpNsiSnrtLqk9BHOWA33+s6D
    egMpK0+tUxxZ5w9Vj7pOM84Qyq1pK0Crj4K3MXcxCHGg/elw9lw/mMAHwt9cS/yq
    b4X/XMZOU9x7JA5ejdQVfdP9HaCrvxy4LIEcc4atmHQuUR88Mabuk9g1Kpg+oLDz
    JZC22jpl199QXaTyxAaBAy41apa9Qs5MUNsV7Z+J5Dw9wpcCAwEAAaNTMFEwHQYD
    VR0OBBYEFJaOkhhpn3fk+ToH3vbMWkG3yKWnMB8GA1UdIwQYMBaAFJaOkhhpn3fk
    +ToH3vbMWkG3yKWnMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIB
    AGeB/0dtzjxOuwVSYpPtKNT5dS865dpkY3ALn1u/Pwdq2XlCMlp2oXFzjHOk2h0H
    Kx6eE1/BdkUEYsx9ZQ2ATLJgPxN8zU3bq1Ng9f70KGrI2FXoeQvbkHfgHuqGRSdA
    DK4ITYq7Jr6/xuyhjTgcuz7GjzKxcWAdqhLiqgLPHAqqIORDIA9kG7rmFzN3vCFK
    s8N2Fqp4bAmWr6LLZ8bAL/HOQoXGsCkZKsEFT3+iXp4QIYc4kVk6OxHrzX1sic1O
    Ml5Tu2bANRHjpiieaJJ2GIdQxnFtLFnYOZ0weWHQzGoR6G5WZlTru8nJO0SxZbxl
    cgHwaNk/INeFEe5q+jip8wfk9Y+mPSiuaU3lipahgohNh3pjgn0CwdE9beJfpNjb
    gMM9Re6/N8ORHrHwDjl7VGD12ddQlYywFVCtzu0InibEB79FKH9Doh5snA9TKZDC
    kgBYGUKjarOL3Je57GwlZiKObXw6faSIK2GrgRDrPpE9/7OJG5l4f/Z7i2lGyWCg
    mNQ1L6O7y/oZBjnqKtdGKcWW8mCQ5PlrTLmYxNXrFxbcwaa1PMnB91dTXzGN5rmU
    wcuyNQZSPT9cLDJrmon8bA5UTXctmU2it+BG0n6nfuCzu0jZWKxQkOxGqLsAMCPo
    8Dg1h20Bkj/sK6/V/xiHk86slJxMrZhn4IujYivCtSje
    -----END CERTIFICATE-----
  session.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDP3NqHKgJFyaGb
    Tegbha4mFlwMKe9CyUBCGZxolkqfeeDjIJco6zcOpYrm0z95Mw5hNTTbY2OD+Rhj
    NzPBWnZ86UNndeV/olVzbuwNxQRP8VmhCBsIVjbRKiNhJrpyiCg0hi20N1zdUHMp
    BOIHtCQYsHj07EkTFlo6pkcnhjI/sRQfAPQHXBEbM3UerPXktVfnYqE5n3fZaFPb
    n5VXWnMOEq1wp0zDVu663+6QVgu64U0QNuU0BxGLeP34+jMcYPrBOb8F6gfrDvzR
    uwkSL+SDfzACVwqUzV6HTHiLhe5/E+p10+XG0QDYJJe9yvDzWy3lqlYQrqPdepRk
    cVmPP4CqzrY6AmfNeHuJ2Zt8Rk1MbSqFoiYMd0LPX7PgQvAMvXvDafZK91YEQSrA
    KnzSkIxUFj6B/X9GFKezzstzN2mwPqnxlc8lOKPdhqFPsowfRmxDyelkLpWX5vNd
    GUk8YrmZ9NWwFVgjzO3oIjOuk2yJKeu0uqT0Ec5YDff6zoN6AykrT61THFnnD1WP
    uk4zzhDKrWkrQKuPgrcxdzEIcaD96XD2XD+YwAfC31xL/Kpvhf9cxk5T3HskDl6N
    1BV90/0doKu/HLgsgRxzhq2YdC5RHzwxpu6T2DUqmD6gsPMlkLbaOmXX31BdpPLE
    BoEDLjVqlr1CzkxQ2xXtn4nkPD3ClwIDAQABAoICAC1OuX9Ow9IMYiJk99vP5qa8
    pvGrzlAjZ9NAm9wcLkXWnhNDzk8H/ic+JCmuEB7N5yt/GndbkZx5ljxCExDpM/yE
    J8IMa6rHapLPsbpKoGcAd4XnK2VEzYwIAFAzzd4bGZBhUuL+UkqXN5LQUqhVNqz/
    Ak54lnEHpUE1bzsJQDir03PylD5qbfwc2kGGd86TTIbN89CIluoXmHe9sCKrP3ro
    zU9J2CyX7U9kci6Z4tKoO1D2dj1B8SwSgmFbv/pGlUG64Y1bdsBgsvDQMOj68XdM
    KN3JtS+8GAervnbDCbo/UBLAzkvo0KNMTpr6+kxBKp7t4vad6m/jQScnodrcf6HW
    idGI+dV+J8T0i3+fhAJzix4KowcRcsuftQEm+fmRJ+cCrPxd39NQWODKalS8usDk
    egAWY3aG0x4dRsldeGuPYhKClDAX2CwhXQgY9qYV+XGE3AtP16REDfkaNGn6ypLY
    dYQgO0cR2ngp4DkKzsmrKP561j6AGCHbI10ecDrwwJgG8EiRq6tpZdxO7iEOJWkk
    oGtfAWbZWQjqROf1fCTgC6Vw/8DNEt3x6MlY544WRyOMK3yBouJPFpCSGPKwVNFR
    5FM9keeIqTr1ubnG7p3vbzlbz6ySCwJNkDJv+VBQ5IB2wtESJTlLT5/XpR8CVxmH
    WbyNGqEnlIAT1RTF7dsxAoIBAQD9u2/2FsQsUpbUcl9aY43sLzcxwcI098ql/uy7
    KEO222Bgy0XJxAX/EmzpK8NFJmBOYOQvF788yVH3DMLo31WLOZoitN4d/2Hf8Ouf
    PwPyQ1WgeKCTjaprWu/Uh3jYCmUKZaXbFdxx6q3lzbqfGprFI5V/RR7R+nZuXcie
    GSaGagcsf3DhcShD9AFf9KPGN6CoKVMUmnPpwRy788KDgrHiPc9XdPf3GXYLkYTi
    dEFHuLqpST+gVVzuquWM+4ZjRuEbdXQ4FvPHPhjWqznJYBWs87TZNkKfSB4xxzzv
    tsoLfuADE1yuI4ea9rq7y12zTgRm1PZROiWF5Z0Q8/tb1ASJAoIBAQDRuHZzaKpj
    fP8Or7a8gD6TFul6I7VdFlRpH4wb900+cRKdSMk8MLcXWamOkkoAlm9ghI6xJcte
    GkHLCm3HosMTZNaayPDQeyhquQnYAWhy+W5cz0IFiSKo12XmYE6DvTWdNcTFTMZk
    94ryCZuoVqdfxRmN1VWTJgOBy8K5hZhNyMlbySi/6e01V6tDWXkongUe5uvFHYeT
    TOKVUmptkeXygn9W2QpAoWa1h00Md9M1Rov5u6UfifBOekNIGIA5uLKkZprbphge
    KHtbrd0fiQYqqxwjPOg6maNtZI4G89goEbEl3LnctWvZHZ4HyyhdtXS7GCGkfmOQ
    lbMGvgqoRgYfAoIBAE9LQW0Vpk73rH1OFPCJhjPWeZhKJigpfCIuLcs7hRXjLxZw
    0CmC4iDZoEGqVIcKvDQiYY06DaCwhbYAPfVKvlAZO0s3XObhBbRXdTs6FUCjvGG+
    8OfL8QNF0weHIsPZU8RRCekSxuau4ZOcnILWbKHJQhIZBs22SUaqdmS6FWkSP5Wv
    ahZ6J4w8+CUFrhznC4UiDP22Wx0lJZazUgmJUZATovWA73FAeryYyH+At1nzqBn5
    czHnG3jW3ZAWluP1panQJfbVbW/JvzdvIUsGhR+ctdrf8ygWAKGr0yZS6Id5Kgas
    CV2+asWJ78d6gZjke8mrKiMuWcWjgVdn+Bi1hIkCggEAaRlDKyT5tq/udiKythai
    xT3HNbFtcz/8f04S/fTaHf+2b2IJjwNuzeHeKhe/xDmfiUQE6lvhZcBM1n7ccx5r
    Gm3/akRnAmOl5o3ilABooq3Dk/k9wd5uoySG6YO79SM+GhHXEXUfO3wegps0CZGb
    gVAaNU0C/KIhQcumQyjjIaAM4NWXeU221XOg3TiakjNWp5zb7MWWqsfuCRzrPwvN
    q9GgFRrhm3AHM9OhVi06iElZXoaeAoczCXEWBKxanhKkW+UbmBXNoldxMomX9fTK
    RVnI2RPt4WgbUXgCARP0cGglWa8a6bN1X7IK/ybdjNChth0qxu+b39pVhHx6hMfK
    ywKCAQBUJMnjobGLtCNbEooG6++IgNxeR23GQWzig915BTEjfbS8qYNcDty3JIxb
    YgtshmAB49cWszM3IU0vyoVEFKgJUP3Frm5LbJBYTbLNFDhGKPDxXg4EbExH+XrW
    UJ6t3q/oY26P6hXUj4VW1Flw+tALF7OBUgfMBps5yZ2ypFP/+Cc5wnmp4L5+aHZb
    my6Keb7yhul80Nr149Mhnzus9tIwvLex/MUk97eWENfRMZMOq6w+PdRAK7FYhSfw
    L/epoLpnyVNSto8j0SJlqs/e3LWOAhRdnqceIWtONpQ0SkOxtXOQr5prqUd58mJV
    iQcxpXHaATwJ8Ipd+gcUsr8SJ/9X
    -----END PRIVATE KEY-----
  svid_session_template.yaml: |
    name: <\session-name-selector>-injector
    version: "0.3"
    predecessor: <\predecessor>
    secrets:
      - name: svid
        kind: x509
        value: |
            <\svid>
        issuer: svid-intermediates
        export:
            session: <\session-name-selector>
            session_hash: <\session-hash-selector>
        private_key: svid_key
      - name: svid-intermediates
        kind: x509-ca
        value: |
            <\svid-intermediates>
        export:
            session: <\session-name-selector>
            session_hash: <\session-hash-selector>
      - name: svid_key
        kind: private-key
        value: |
            <\svid-key>
        export:
            session: <\session-name-selector>
            session_hash: <\session-hash-selector>
    
  ca_session_template.yaml: |
    name: <\trust-bundle-session-name>-injector
    version: "0.3"
    predecessor: <\predecessor>
    secrets:
      - name: spire-ca
        kind: x509-ca
        export_public: true
        value: |
            <\trust-bundle>

  fed_bundles_session_template.yaml: |
    name: <\fed-bundles-session-name>
    version: "0.3"
    predecessor: <\predecessor>
    secrets:
      - name: spire-federated-bundles
        kind: x509-ca
        export_public: true
        value: |
            <\federated-bundles>

  # Ignored in silvamatteus/spire-agent-scone:lastest
  # to simplify the demonstration.
  # In a real scenario, a valid trust anchor must be set. 
  trustanchor.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBSzCB86ADAgECAghOOPIfwEXXGjAKBggqhkjOPQQDAjAOMQwwCgYDVQQDDANj
    YXMwHhcNMjExMTE2MTgxODU2WhcNMjIxMTE2MTgxODU2WjAXMRUwEwYDVQQDDAxj
    YXMtaW5zdGFuY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASEZpwAxkvHUziS
    mmln3J94ncagcw9WrTBcLTdneJl9bMl+EWQP139sSQLbJP0AlQqx13BP0qTh7f8Z
    vbD4A1aZozIwMDAdBgNVHQ4EFgQUqRB0UpdCbkK8k1lHqvBl5a1xJ8IwDwYDVR0T
    AQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiAqozKMRFS0m9qT5wGgxbUjkJnE
    RmjKNKwEK2KLB9wMiwIgfVcILdZ/kXPdVukEsOEOJ8/aseV4lTX57sXdL4mYW6w=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIBRDCB66ADAgECAgkAxwc2p5TXQQowCgYIKoZIzj0EAwIwDjEMMAoGA1UEAwwD
    Y2FzMB4XDTIxMTExNjE4MTg1NloXDTIyMTExNjE4MTg1NlowDjEMMAoGA1UEAwwD
    Y2FzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEABKfJw2kSav0+P/gE55rNQJV
    bZvZO523BtyvngCw0xSLolxKRD8giDAjH2JEzJMSK754x6GnzoFElZrGVBdgXKMy
    MDAwHQYDVR0OBBYEFLCnrlBxlEEhZJBsIaEpM7Qb9wUjMA8GA1UdEwEB/wQFMAMB
    Af8wCgYIKoZIzj0EAwIDSAAwRQIgIE0vKM5BZZ1D3uTNIUbKvPxG6rpaMmdz+SVX
    k5N/SWwCIQCZ6SHAZbTi1bjmo3937HC9roHusgQ6R2Sods0H5FXspQ==
    -----END CERTIFICATE-----
